services:
  backend:
    container_name: task_backend
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./config/.local.env
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:17
    container_name: postgres_container
    restart: always
    env_file:
      - ./config/.local.env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: